name: Python Application

# Este workflow se ejecutará cuando haya un push a la rama principal o se abra un pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Definir los jobs
jobs:
  build:
    # Indicar que el job se ejecuta en un runner Ubuntu (máquina Linux)
    runs-on: ubuntu-latest

    # Configurar los pasos para ejecutar
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'  # Puedes especificar la versión de Python que necesites

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest  # Si tienes pruebas con pytest

    - name: Run the application
      run: |
        python ms.py  # Ajusta esto según tu proyecto
